project:
  type: manuscript

manuscript:
  article: index.qmd

author:
  - name: "Melissa May"
      corresponding: true
  - name: "Ainsley Denham"
  - name: "Ava Madalinski"

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



